In [1]:
import numpy as np
import ENV

In [1]:
%pip install matplotlib

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 11.2/11.2 MB 2.8 MB/s eta 0:00:0000:0100:01
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/5c/f9/695d6bedebd747e5eb0fe8fad57b72fdf25411273a39791cde838d5a8f51/cycler-0.11.0-py3-none-any.whl (6.4 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.6/1.6 MB 2.1 MB/s eta 0:00:0000:0100:010m
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.1/3.1 MB 2.7 MB/s eta 0:00:00a 0:00:01
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 930.9/930.9 kB 2.7 MB/s eta 0:00:00a 0:00:01
Note: you may need to restart the kernel to use updated packages.


In [6]:
import gym
envv=gym.make('CartPole-v0')
envv.reset()
for i in range(20):
    print(envv.step(0))

(array([-0.00279816, -0.18650424, -0.04548791,  0.2406923 ]), 1.0, False, {})
(array([-0.00652824, -0.38094788, -0.04067407,  0.51868723]), 1.0, False, {})
(array([-0.0141472 , -0.57547428, -0.03030032,  0.79828063]), 1.0, False, {})
(array([-0.02565669, -0.77016771, -0.01433471,  1.08127978]), 1.0, False, {})
(array([-0.04106004, -0.96509753,  0.00729088,  1.36943021]), 1.0, False, {})
(array([-0.06036199, -1.16030994,  0.03467949,  1.66438454]), 1.0, False, {})
(array([-0.08356819, -1.35581794,  0.06796718,  1.96766394]), 1.0, False, {})
(array([-0.11068455, -1.55158904,  0.10732046,  2.28060954]), 1.0, False, {})
(array([-0.14171633, -1.7475303 ,  0.15293265,  2.60432214]), 1.0, False, {})
(array([-0.17666693, -1.94347075,  0.20501909,  2.9395896 ]), 1.0, False, {})
(array([-0.21553635, -2.13914154,  0.26381088,  3.28680316]), 1.0, True, {})
(array([-0.25831918, -2.33415523,  0.32954695,  3.64586731]), 0.0, True, {})
(array([-0.30500228, -2.52798655,  0.40246429,  4.01611155]), 0.0,

In [3]:
np.inf-1

inf

In [2]:
random_uniform_int=lambda low,high:(lambda x:np.random.randint(low,high,x)+0.0)
random_loc=lambda low,high:(lambda x:np.random.choice(np.arange(low,high),x,replace=False))
unit_loc=lambda s,e:(lambda x:np.linspace(s,e,x+2)[1:-1])
num_cars=5
num_units=3
bs_cover=1000
config={'source':lambda x:int(random_uniform_int(num_units,num_cars+num_units)(x)),
        'sc':random_uniform_int(1000,10000),
        'sr':random_uniform_int(10,40),
        'tp':random_uniform_int(1,5),
        'pfr':random_uniform_int(5000,10000),
        'pf':random_uniform_int(200,500),
        'plr':unit_loc(0,bs_cover),
        'pl':random_loc(0,100),
        'pd':random_uniform_int(2,6),
        'ps':random_uniform_int(60,100),
        'pbr':random_uniform_int(200,500),
        'pb':random_uniform_int(50,100),
        'ppr':random_uniform_int(500,1000),
        'pp':random_uniform_int(100,200),
        'pg':random_uniform_int(10,100),
        'whitenoise':1,
        'alpha':2
}

In [3]:
ENV.ADENVBASE.attr_code

{'pf': 'processor_frequency',
 'pl': 'processor_location',
 'pd': 'processor_distancefromroad',
 'ps': 'processor_speed',
 'pb': 'processor_bandwidth',
 'pp': 'processor_power',
 'pg': 'processor_gain',
 'pw': 'processor_wait',
 'tp': 'time_pass',
 'sc': 'subtask_cycle',
 'sr': 'subtask_returnsize',
 'sl': 'subtask_location',
 'whitenoise': 'whitenoise',
 'alpha': 'alpha',
 'source': 'source'}

In [4]:
np.random.seed(1)

In [14]:
num_subtasks=7
env=ENV.ADENVBASE(num_cars+num_units,num_subtasks,num_units,bs_cover,config)
env.reset()
for i in range(10):
    action=np.random.randint(low=0,high=num_cars+num_units,size=(2,num_subtasks))
    a={pro:[sub for sub in range(num_subtasks) if action[0,sub]==pro] for pro in set(action[0])}
    for pro,sub in a.items():
        for i,x in enumerate(sub):
            action[1,x]=i+1
    time_exe,time_wait,time_return=env.step(action)
    print('time_exe: ',['{0:<5.2f}'.format(t) for t in time_exe])
    print('time_wait: ',['{0:<5.2f}'.format(t) for t in time_wait])
    print('time_return: ',['{0:<5.2f}'.format(t) for t in time_return])
    wait=['{0:<5.2f}'.format(num) for num in env.processor_wait]
    return_wait=['{0:<5.2f}'.format(num) for num in env.processor_lastaway_wait]
    print('processor_wait: ',wait)
    print('return_wait: ',return_wait)
    print()

time_exe:  ['20.02', '18.75', '31.20', '34.85', '4.85 ', '8.53 ', '7.57 ']
time_wait:  ['0.00 ', '0.00 ', '0.00 ', '31.20', '0.00 ', '66.06', '0.00 ']
time_return:  ['0.00 ', '0.01 ', '0.10 ', '0.06 ', '0.04 ', '0.08 ', '0.00 ']
processor_wait:  ['0.00 ', '0.00 ', '0.00 ', '0.00 ', '0.00 ', '6.70 ', '34.50', '79.15']
return_wait:  ['0.00 ', '0.00 ', '0.00 ', '0.00 ', '0.00 ', '0.04 ', '0.01 ', '0.08 ']

time_exe:  ['23.19', '13.73', '0.82 ', '1.58 ', '6.37 ', '0.37 ', '16.90']
time_wait:  ['0.00 ', '0.00 ', '0.00 ', '0.00 ', '0.00 ', '0.00 ', '34.50']
time_return:  ['0.00 ', '0.02 ', '0.07 ', '0.12 ', '0.00 ', '0.00 ', '0.07 ']
processor_wait:  ['0.00 ', '0.64 ', '0.95 ', '0.00 ', '26.46', '12.07', '67.30', '0.00 ']
return_wait:  ['0.00 ', '0.07 ', '0.12 ', '0.00 ', '0.02 ', '0.04 ', '0.07 ', '0.08 ']

time_exe:  ['26.42', '9.11 ', '23.58', '17.49', '35.48', '29.88', '0.70 ']
time_wait:  ['0.00 ', '67.30', '0.00 ', '26.46', '0.00 ', '0.00 ', '0.95 ']
time_return:  ['0.00 ', '0.06 ', '0

In [6]:
print(env.processor_speed,env.processor_location,env.processor_distancefromroad)

[ 0.  0.  0. 78. 78. 78. 78. 78.] [ 250.  500.  750. 2198. 2150. 2162. 2188. 2175.] [0. 0. 0. 5. 3. 2. 3. 2.]


In [12]:
a=['{0:<5.2f}'.format(num) for num in env.processor_wait]

In [25]:
a=np.array([[1,0,1],
            [3,1,0]])

In [24]:
1==1.0

True

In [31]:
l=[np.where(k>0)[0] for k in a.T]
u=[np.random.choice(x) for x in l]
u

[1, 1, 0]

In [13]:
a[1]==True

array([False,  True, False])

In [16]:
a[1].where(x>0)

AttributeError: 'numpy.ndarray' object has no attribute 'where'

In [22]:
np.where(a[1]>0)[0]

array([0])

In [21]:
a

array([0, 1])

In [33]:
np.inf>0

True

In [1]:
import scipy.integrate as si
import numpy as np
F=lambda f:(lambda x:si.quad(f,0,x)[0])
f=lambda x:1
F(f)(np.inf)

/home/zy/anaconda3/envs/py36/lib/python3.6/site-packages/ipykernel_launcher.py:3: IntegrationWarning: The integral is probably divergent, or slowly convergent.
  This is separate from the ipykernel package so we can avoid doing imports until


-1.0

In [2]:
np.random.random??

Docstring:
random(size=None)

Return random floats in the half-open interval [0.0, 1.0). Alias for
`random_sample` to ease forward-porting to the new random API.
Type:      builtin_function_or_method


In [3]:
np.random.uniform??

Docstring:
uniform(low=0.0, high=1.0, size=None)

Draw samples from a uniform distribution.

Samples are uniformly distributed over the half-open interval
``[low, high)`` (includes low, but excludes high).  In other words,
any value within the given interval is equally likely to be drawn
by `uniform`.

Parameters
----------
low : float or array_like of floats, optional
    Lower boundary of the output interval.  All values generated will be
    greater than or equal to low.  The default value is 0.
high : float or array_like of floats
    Upper boundary of the output interval.  All values generated will be
    less than high.  The default value is 1.0.
size : int or tuple of ints, optional
    Output shape.  If the given shape is, e.g., ``(m, n, k)``, then
    ``m * n * k`` samples are drawn.  If size is ``None`` (default),
    a single value is returned if ``low`` and ``high`` are both scalars.
    Otherwise, ``np.broadcast(low, high).size`` samples are drawn.

Returns
-------
out : n