In [1]:
import numpy as np
import torch
import AGENT_NET
from numpy.random import RandomState,MT19937,SeedSequence
from collections import deque
import copy

In [4]:
a=np.arange(5)
a[a[0:3]]

array([0, 1, 2])

In [3]:
a=torch.arange(15).view(3,-1).type(torch.float)
d=torch.nn.BatchNorm1d(5)
d(a)

tensor([[-1.2247e+00, -1.2247e+00, -1.2247e+00, -1.2247e+00, -1.2247e+00],
        [-1.4901e-08,  2.9802e-08, -4.4703e-08,  0.0000e+00, -7.4506e-08],
        [ 1.2247e+00,  1.2247e+00,  1.2247e+00,  1.2247e+00,  1.2247e+00]],
       grad_fn=<NativeBatchNormBackward0>)

In [6]:
a

tensor([[ 0.,  1.,  2.,  3.,  4.],
        [ 5.,  6.,  7.,  8.,  9.],
        [10., 11., 12., 13., 14.]])

In [8]:
1/(a-1e-14)

tensor([[-1.0000e+14,  1.0000e+00,  5.0000e-01,  3.3333e-01,  2.5000e-01],
        [ 2.0000e-01,  1.6667e-01,  1.4286e-01,  1.2500e-01,  1.1111e-01],
        [ 1.0000e-01,  9.0909e-02,  8.3333e-02,  7.6923e-02,  7.1429e-02]])

In [4]:
import numpy as np
import ENV
import AC
import torch
import rl_utils
from matplotlib import pyplot as plt
from TEST import model_test
from RANDOMAGENT import RANDOMAGENT
from copy import deepcopy

np.random.seed(1)
torch.manual_seed(0)
actor_lr = 1e-3
critic_lr = 1e-2
num_episodes = 1000
gamma = 0.98
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")

random_uniform_int=lambda low,high:(lambda x:np.random.randint(low,high,x))
random_uniform_float=lambda low,high:(lambda x:np.random.uniform(low,high,x))
random_loc=lambda low,high:(lambda x:np.random.choice(np.arange(low,high),x,replace=False).astype('float'))
unit_loc=lambda s,e:(lambda x:np.linspace(s,e,x+1)[:-1])
num_cars=2
num_units=2
bs_cover=1000
config={'source':random_uniform_int(num_units,num_cars+num_units),
        'sc':random_uniform_int(100,200),
        'sr':random_uniform_int(500,1000),
        'tp':random_uniform_float(1,3),
        'pfr':random_uniform_int(5000,10000),
        'pf':random_uniform_int(2000,5000),
        'plr':unit_loc(0,bs_cover),
        'pl':random_loc(0,bs_cover//10),
        'pd':random_uniform_float(2,6),
        'ps':random_uniform_float(60,100),
        'pbr':random_uniform_int(2000,5000),
        'pb':random_uniform_int(2000,4000),
        'ppr':random_uniform_int(200,300),
        'pp':random_uniform_int(100,200),
        'pg':random_uniform_int(20,40),
        'pcr':random_uniform_float(50,300),
        'pc':random_uniform_float(10,100),
        'whitenoise':1,
        'alpha':2}

num_subtasks=2
time_base=100

env=ENV.ENVONE(time_base,num_processors=num_cars+num_units,
num_subtasks=num_subtasks,num_roadsideunits=num_units,basestation_cover=bs_cover,config=config)

w=(env.num_processors,env.num_processor_attributes-1+env.num_subtasks)
agent=AC.ActorCritic(w,num_subtasks,actor_lr,critic_lr,gamma,device,clip_grad=0.1,conv=1)
return_list=rl_utils.train_on_policy_agent(env,agent,num_episodes)

model_test(env,agent,1,num_subtasks,cycles=1)
print('next_agent##################################################')
r_agent=RANDOMAGENT(w,num_subtasks)
model_test(env,r_agent,1,num_subtasks,cycles=1)

time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
episode:9, reward:-9.0
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
episode:19, reward:-9.0
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
episode:29, reward:-8.577481291672566
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
episode:39, reward:-7.325691938263242
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
episode:49, reward:-8.00165

[-1.5705949427009438]

In [3]:
import numpy as np
import ENV_AGENT
import ENV
import AC
import torch
import rl_utils
from collections import deque
from TEST import model_test
from RANDOMAGENT import RANDOMAGENT
from copy import deepcopy

np.random.seed(1)
torch.manual_seed(0)

actor_lr = 1e-3
critic_lr = 1e-2
num_episodes = 1000
gamma = 0.98
device = torch.device("cuda") if torch.cuda.is_available() else torch.device("cpu")
#device=torch.device('cpu')

random_uniform_int=lambda low,high:(lambda x:np.random.randint(low,high,x))
random_uniform_float=lambda low,high:(lambda x:np.random.uniform(low,high,x))
random_loc=lambda low,high:(lambda x:np.random.choice(np.arange(low,high),x,replace=False).astype('float'))
unit_loc=lambda s,e:(lambda x:np.linspace(s,e,x+1)[:-1])
num_cars=4
num_units=1
bs_cover=1000
config={'source':random_uniform_int(num_units,num_cars+num_units),
        'sc':random_uniform_int(100,200),
        'sr':random_uniform_int(100,200),
        'tp':random_uniform_float(1,3),
        'pfr':random_uniform_int(900,1000),
        'pf':random_uniform_int(400,500),
        'plr':unit_loc(0,bs_cover),
        'pl':random_loc(0,bs_cover//10),
        'pd':random_uniform_float(2,6),
        'ps':random_uniform_float(60,100),
        'pbr':random_uniform_int(4000,5000),
        'pb':random_uniform_int(2000,4000),
        'ppr':random_uniform_int(200,300),
        'pp':random_uniform_int(100,200),
        'pg':random_uniform_int(20,40),
        'pcr':random_uniform_float(50,300),
        'pc':random_uniform_float(10,100),
        'whitenoise':1,
        'alpha':2}

config_in=deepcopy(config)
config_in['tp']=random_uniform_float(8,10)
num_subtasks=2
time_base=100

deque_1=deque()
proin=ENV_AGENT.PROIN(config_in,1000,deque_1)
proin.run()

deque_2=deque()

env_agent=ENV_AGENT.ENV_AGENT(time_base=time_base,num_processors=num_cars+num_units,
num_subtasks=num_subtasks,num_roadsideunits=num_units,basestation_cover=bs_cover,config=config)

w=(env_agent.num_processors,env_agent.num_processor_attributes-1+env_agent.num_subtasks)
agent=AC.ActorCritic(w,num_subtasks,actor_lr,critic_lr,gamma,device,clip_grad=0.1,conv=1)

env_agent.set_agent(agent)

bigenv=ENV_AGENT.BIGENV_ONE([deque_1],[deque_2],env_agent)
return_list=rl_utils.train_on_policy_agent(bigenv,bigenv.agent,num_episodes)

model_test(bigenv,bigenv.agent,1,num_subtasks,cycles=1)
print('next_agent##################################################')
r_agent=RANDOMAGENT(w,num_subtasks)
model_test(bigenv,r_agent,1,num_subtasks,cycles=1)


time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
episode:9, reward:-9.535127196571299
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
episode:19, reward:-12.364936820839933
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
episode:29, reward:-6.843043525689292
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
episode:39, reward:-13.718726891880904
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too long
time is too lo

"env=ENV.ENVONE(time_base,num_processors=num_cars+num_units,\nnum_subtasks=num_subtasks,num_roadsideunits=num_units,basestation_cover=bs_cover,config=config)\nstate=env.reset()\nprint('state:{}'.format(state[0]))\naction=agent.take_action(state)\nprint('action:{}'.format(action))\nnext_state, reward, done, _ = env.step(action)\nprint('next_state:{}'.format(next_state[0]))"

In [2]:
a=np.arange(12).reshape(3,4)
a[::-1]

array([[ 8,  9, 10, 11],
       [ 4,  5,  6,  7],
       [ 0,  1,  2,  3]])

In [11]:
d=deque()
d.extendleft([2,3,5,5,6,7])

In [12]:
d

deque([7, 6, 5, 5, 3, 2])

In [3]:
a=np.arange(4).reshape(2,2)
a[list(range(2)),range(2)]

array([0, 3])

In [ ]:
copy.deepcopy

In [1]:
from collections import deque

In [2]:
d=deque(maxlen=1)
d.append(2)
d.append(3)

deque([3])

In [54]:
class NN:
    yy=1
    locals()['yy']=2
    def ggg(self):
        self.yy=3
        print(locals())
        print(vars())
        print(globals()['self.yy'])

In [59]:
b=NN()
c=NN()
l=[b,c]
l.remove(b)
l[0].yy

2

In [6]:
a={1}
a.pop()
a.pop()
a

KeyError: 'pop from an empty set'

In [17]:
np.random.choice(5,5)

array([2, 1, 0, 4, 2])

In [24]:
a=np.array([1,2,3,4,5])
b=slice(1,None)
a[b]

array([2, 3, 4, 5])

In [25]:
u=set(range(10)[b])

In [26]:
y={1,2}
a[list(y)]

array([2, 3])

In [4]:
torch.nn.utils.clip_grad_norm_??

Signature:
torch.nn.utils.clip_grad_norm_(
    parameters: Union[torch.Tensor, Iterable[torch.Tensor]],
    max_norm: float,
    norm_type: float = 2.0,
    error_if_nonfinite: bool = False,
) -> torch.Tensor
Source:   
def clip_grad_norm_(
        parameters: _tensor_or_tensors, max_norm: float, norm_type: float = 2.0,
        error_if_nonfinite: bool = False) -> torch.Tensor:
    r"""Clips gradient norm of an iterable of parameters.

    The norm is computed over all gradients together, as if they were
    concatenated into a single vector. Gradients are modified in-place.

    Args:
        parameters (Iterable[Tensor] or Tensor): an iterable of Tensors or a
            single Tensor that will have gradients normalized
        max_norm (float or int): max norm of the gradients
        norm_type (float or int): type of the used p-norm. Can be ``'inf'`` for
            infinity norm.
        error_if_nonfinite (bool): if True, an error is thrown if the total
            norm of the gr

In [7]:
def gg(**kwargs):
    return kwargs['kk']

In [44]:
dic=dict(gg=99)
dic

{'gg': 99}

In [36]:
rs = RandomState(MT19937(SeedSequence(123456789)))
np.random.rand()

0.4458734577953869

In [33]:
SeedSequence(123456789)

SeedSequence(
    entropy=123456789,
)

In [5]:
net=AGENT_NET.PolicyNet_FC((3,4),5,'cuda')

In [6]:
print(*[(name, param.shape) for name, param in net.named_parameters()])

('fc.0.weight', torch.Size([128, 22])) ('fc.0.bias', torch.Size([128])) ('fc.2.weight', torch.Size([128, 128])) ('fc.2.bias', torch.Size([128])) ('policy_layer.0.weight', torch.Size([3, 128])) ('policy_layer.0.bias', torch.Size([3])) ('policy_layer.1.weight', torch.Size([3, 128])) ('policy_layer.1.bias', torch.Size([3])) ('policy_layer.2.weight', torch.Size([3, 128])) ('policy_layer.2.bias', torch.Size([3])) ('policy_layer.3.weight', torch.Size([3, 128])) ('policy_layer.3.bias', torch.Size([3])) ('policy_layer.4.weight', torch.Size([3, 128])) ('policy_layer.4.bias', torch.Size([3])) ('prior_layer.0.weight', torch.Size([5, 128])) ('prior_layer.0.bias', torch.Size([5])) ('prior_layer.1.weight', torch.Size([5, 128])) ('prior_layer.1.bias', torch.Size([5])) ('prior_layer.2.weight', torch.Size([5, 128])) ('prior_layer.2.bias', torch.Size([5])) ('prior_layer.3.weight', torch.Size([5, 128])) ('prior_layer.3.bias', torch.Size([5])) ('prior_layer.4.weight', torch.Size([5, 128])) ('prior_layer.4

In [8]:
for layer in net.parameters():
    print(layer)

Parameter containing:
tensor([[-0.0861, -0.1270, -0.1079,  ..., -0.1422, -0.0223,  0.0142],
        [-0.1760, -0.0213, -0.0977,  ..., -0.0348,  0.1231,  0.0645],
        [ 0.2114,  0.1172, -0.1139,  ..., -0.0162,  0.1681, -0.0054],
        ...,
        [-0.0612,  0.1756, -0.0649,  ..., -0.1031, -0.1208,  0.0647],
        [-0.2126, -0.2049,  0.0721,  ...,  0.0484, -0.1630,  0.1321],
        [ 0.1406, -0.0698, -0.0300,  ...,  0.0490, -0.1279, -0.1770]],
       requires_grad=True)
Parameter containing:
tensor([ 0.1184,  0.0262, -0.0065, -0.0353, -0.0213,  0.0410,  0.0990, -0.0104,
         0.0157, -0.0411,  0.0603,  0.1483,  0.1729,  0.1120, -0.0699, -0.1122,
        -0.0936,  0.1558,  0.0056, -0.1398, -0.0548,  0.1497, -0.1778, -0.0031,
        -0.1461, -0.0767, -0.1488, -0.1624, -0.0893,  0.1609,  0.1269, -0.1861,
        -0.0052, -0.1760,  0.1534, -0.0415, -0.0185, -0.1631,  0.0101,  0.1530,
        -0.1825,  0.1450,  0.0258, -0.1467,  0.1828, -0.0733,  0.1394, -0.1479,
        -0.2089

In [6]:
net.parameters??

Signature: net.parameters(recurse: bool = True) -> Iterator[torch.nn.parameter.Parameter]
Source:   
    def parameters(self, recurse: bool = True) -> Iterator[Parameter]:
        r"""Returns an iterator over module parameters.

        This is typically passed to an optimizer.

        Args:
            recurse (bool): if True, then yields parameters of this module
                and all submodules. Otherwise, yields only parameters that
                are direct members of this module.

        Yields:
            Parameter: module parameter

        Example::

            >>> for param in model.parameters():
            >>>     print(type(param), param.size())
            <class 'torch.Tensor'> (20L,)
            <class 'torch.Tensor'> (20L, 1L, 5L, 5L)

        """
        for name, param in self.named_parameters(recurse=recurse):
            yield param
File:      ~/anaconda3/envs/py39/lib/python3.9/site-packages/torch/nn/modules/module.py
Type:      method


In [12]:
a=torch.arange(4).view(2,2).float()
a[0]=torch.tensor([1,1])
torch.nn.functional.softmax(a,dim=1)

tensor([[0.5000, 0.5000],
        [0.2689, 0.7311]])

In [2]:
l=[]
l[-1]

IndexError: list index out of range

In [31]:
%pip install tqdm

Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.4/78.4 kB 839.2 kB/s eta 0:00:00 0:00:01m
Note: you may need to restart the kernel to use updated packages.


In [30]:
a=(1,2)
a[0:0]==()

True

In [4]:
a=torch.arange(4)
a.int()

tensor([0, 1, 2, 3], dtype=torch.int32)

In [5]:
a=np.arange(4)
b=torch.zeros((4,4))
b[:,list(a)]
b.T

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [98]:
n=3
out_puts=np.concatenate([np.arange(1,4),np.arange(1,4),np.arange(1,4)],0)
torch.tensor(out_puts)

tensor([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [96]:
1/6*2/5

0.06666666666666667

In [94]:
G=lambda i:out_puts[i][actions[i]]/(out_puts[i].sum()-out_puts[i][actions[:i]].sum())*G(i+1) if i<n else 1

In [95]:
G(0)

0.06666666666666667

In [71]:
f=lambda x:x[-1]*f(x[:-1]) if x!=[] else 1

In [74]:
f([1,2,3,4])

24

In [69]:
y=torch.rand((1,1,3,6))
torch.tensor(np.delete(y.numpy(),[],2),dtype=torch.float)

tensor([[[[0.6842, 0.5458, 0.5271, 0.7299, 0.5929, 0.6527],
          [0.6924, 0.6810, 0.2899, 0.9261, 0.7633, 0.3941],
          [0.6905, 0.6283, 0.2256, 0.4465, 0.3406, 0.0311]]]])

In [30]:
a=torch.arange(1,5).view(1,-1).float().to('cpu')

In [17]:
b=torch.nn.Softmax(a)
torch.distributions.S

TypeError: 'Tensor' object is not callable

In [10]:
torch.nn.Softmax(a)

Softmax(dim=tensor([[1., 2., 3., 4.]]))

In [10]:
a=torch.arange(6).view(2,3)

In [11]:
a.sum(axis=1,keepdim=True)

tensor([[ 3],
        [12]])

In [9]:
a[:,[0]]

tensor([[0],
        [3]])

In [67]:
c=torch.distributions.Categorical(a).sample()
c

tensor(5)

In [50]:
c+1

TypeError: unsupported operand type(s) for +: 'Categorical' and 'int'

In [40]:
type(np.random.randint(1,5,1)[0])

numpy.int64

In [31]:
np.concatenate((a,b),0)

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [24]:
gg=a.astype('float32')

In [25]:
gg.dtype

dtype('float64')

In [26]:
a

array([[0, 1, 2, 3, 4, 5]])